export const PALETTES = [
  'slate',
  'gray',
  'zinc',
  'neutral',
  'stone',
  'red',
  'orange',
  'amber',
  'yellow',
  'lime',
  'green',
  'emerald',
  'teal',
  'cyan',
  'sky',
  'blue',
  'indigo',
  'violet',
  'purple',
  'fuchsia',
  'pink',
  'rose',
] as const

export const LOCALES = ['en', 'da', 'de', 'fr'] as const

export const SHADES = ['50', '100', '200', '300', '400', '500', '600', '700', '800', '900', '950'] as const

export const COLOR_TRANSLATIONS = {
  da: {
    slate: 'Skifer',
    gray: 'Grå',
    zinc: 'Zink',
    neutral: 'Neutral',
    stone: 'Sten',
    red: 'Rød',
    orange: 'Orange',
    amber: 'Rav',
    yellow: 'Gul',
    lime: 'Lime',
    green: 'Grøn',
    emerald: 'Smaragd',
    teal: 'Blågrøn',
    cyan: 'Cyan',
    sky: 'Himmelblå',
    blue: 'Blå',
    indigo: 'Indigo',
    violet: 'Violet',
    purple: 'Lilla',
    fuchsia: 'Fuchsia',
    pink: 'Lyserød',
    rose: 'Rose',
  },
  de: {
    slate: 'Schiefer',
    gray: 'Grau',
    zinc: 'Zink',
    neutral: 'Neutral',
    stone: 'Stein',
    red: 'Rot',
    orange: 'Orange',
    amber: 'Bernstein',
    yellow: 'Gelb',
    lime: 'Limette',
    green: 'Grün',
    emerald: 'Smaragd',
    teal: 'Blaugrün',
    cyan: 'Cyan',
    sky: 'Himmelblau',
    blue: 'Blau',
    indigo: 'Indigo',
    violet: 'Violett',
    purple: 'Lila',
    fuchsia: 'Fuchsia',
    pink: 'Rosa',
    rose: 'Rose',
  },
  fr: {
    slate: 'Ardoise',
    gray: 'Gris',
    zinc: 'Zinc',
    neutral: 'Neutre',
    stone: 'Pierre',
    red: 'Rouge',
    orange: 'Orange',
    amber: 'Ambre',
    yellow: 'Jaune',
    lime: 'Citron vert',
    green: 'Vert',
    emerald: 'Émeraude',
    teal: 'Sarcelle',
    cyan: 'Cyan',
    sky: 'Bleu ciel',
    blue: 'Bleu',
    indigo: 'Indigo',
    violet: 'Violet',
    purple: 'Pourpre',
    fuchsia: 'Fuchsia',
    pink: 'Rose',
    rose: 'Rose',
  },
} as const