/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'project-types': ProjectType;
    'product-types': ProductType;
    products: Product;
    projects: Project;
    'project-groups': ProjectGroup;
    courses: Course;
    'course-chapters': CourseChapter;
    'course-pages': CoursePage;
    'course-content': CourseContent;
    palettes: Palette;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    users: {
      viewableProjects: 'projects';
      editableProjects: 'projects';
      managedProjects: 'projects';
    };
    'project-types': {
      projects: 'projects';
    };
    'product-types': {
      products: 'products';
    };
    products: {
      projectGroups: 'project-groups';
    };
    projects: {
      groups: 'project-groups';
      courses: 'courses';
    };
    courses: {
      chapters: 'course-chapters';
      products: 'products';
    };
    'course-chapters': {
      pages: 'course-pages';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'project-types': ProjectTypesSelect<false> | ProjectTypesSelect<true>;
    'product-types': ProductTypesSelect<false> | ProductTypesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    'project-groups': ProjectGroupsSelect<false> | ProjectGroupsSelect<true>;
    courses: CoursesSelect<false> | CoursesSelect<true>;
    'course-chapters': CourseChaptersSelect<false> | CourseChaptersSelect<true>;
    'course-pages': CoursePagesSelect<false> | CoursePagesSelect<true>;
    'course-content': CourseContentSelect<false> | CourseContentSelect<true>;
    palettes: PalettesSelect<false> | PalettesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale:
    | ('false' | 'none' | 'null')
    | false
    | null
    | ('en' | 'da' | 'de' | 'fr')
    | ('en' | 'da' | 'de' | 'fr')[];
  globals: {};
  globalsSelect: {};
  locale: 'en' | 'da' | 'de' | 'fr';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Authenticated users with global roles and project-scoped memberships.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  roles?: ('super-admin' | 'user')[] | null;
  viewableProjects?: {
    docs?: (number | Project)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  editableProjects?: {
    docs?: (number | Project)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  managedProjects?: {
    docs?: (number | Project)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Top-level workspaces that contain groups, courses, and access memberships.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Select the project type (uses project-types collection)
   */
  projectType: number | ProjectType;
  /**
   * Child project groups
   */
  groups?: {
    docs?: (number | ProjectGroup)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  courses?: {
    docs?: (number | Course)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Users who can view this project.
   */
  viewers?: (number | User)[] | null;
  /**
   * Users who can edit this project and its child content.
   */
  editors?: (number | User)[] | null;
  /**
   * Users who can manage project memberships.
   */
  managers?: (number | User)[] | null;
  viewerSummary?: string | null;
  editorSummary?: string | null;
  managerSummary?: string | null;
  /**
   * Business lifecycle separate from Payload draft and published status.
   */
  lifecycle: 'active' | 'archived';
  isPublic?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Reference types that classify projects and help organize delivery work.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "project-types".
 */
export interface ProjectType {
  id: number;
  title: string;
  description?: string | null;
  projects?: {
    docs?: (number | Project)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Project-scoped bundles of products that make the project structure easier to inspect.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "project-groups".
 */
export interface ProjectGroup {
  id: number;
  /**
   * Parent project for this group
   */
  project: number | Project;
  /**
   * Products contained in this project group
   */
  products?: (number | Product)[] | null;
  title: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Reusable product records that can be linked into courses and grouped inside projects.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  title: string;
  isbn?: string | null;
  /**
   * Optional product type (uses product-types collection)
   */
  productType?: (number | null) | ProductType;
  /**
   * Courses associated with this product
   */
  courses?: (number | Course)[] | null;
  projectGroups?: {
    docs?: (number | ProjectGroup)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Reference types that classify products across courses and project groups.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-types".
 */
export interface ProductType {
  id: number;
  title: string;
  products?: {
    docs?: (number | Product)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Project-scoped course frontpages with reusable chapter and product associations.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses".
 */
export interface Course {
  id: number;
  /**
   * Hero image for the course frontpage. Select from the media library or upload a new scoped image asset.
   */
  hero: number | Media;
  title: string;
  isbn?: string | null;
  /**
   * Optional localized introduction for the course frontpage.
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Which project this course belongs to
   */
  project: number | Project;
  /**
   * Chapters that belong to this course frontpage.
   */
  chapters?: {
    docs?: (number | CourseChapter)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  products?: {
    docs?: (number | Product)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Shared asset library for images, video, GeoGebra, ThingLink, downloads, and future media types.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * High-level media type so the library can grow beyond image uploads cleanly.
   */
  kind: 'image' | 'video' | 'geogebra' | 'thinglink' | 'download' | 'other';
  /**
   * Choose the narrowest level where this file should be available in the media library.
   */
  availabilityScope: 'project' | 'projectGroup' | 'product' | 'course';
  /**
   * Top-level project ownership for this file.
   */
  project: number | Project;
  /**
   * Limit this file to a specific product group within the chosen project.
   */
  projectGroup?: (number | null) | ProjectGroup;
  /**
   * Limit this file to a specific product.
   */
  product?: (number | null) | Product;
  /**
   * Limit this file to a specific course inside the chosen project.
   */
  course?: (number | null) | Course;
  /**
   * Accessibility text for visual media. Keep this populated for images and previews.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Structured chapters that live inside a course frontpage and group reusable pages.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "course-chapters".
 */
export interface CourseChapter {
  id: number;
  /**
   * Hero image for this chapter. Select from the media library or upload a new scoped image asset.
   */
  hero: number | Media;
  title: string;
  /**
   * Optional localized overview for the chapter.
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Which course frontpage this chapter belongs to.
   */
  course: number | Course;
  /**
   * Pages collected under this chapter.
   */
  pages?: {
    docs?: (number | CoursePage)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Localized course pages that belong to chapters and assemble reusable content items in order.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "course-pages".
 */
export interface CoursePage {
  id: number;
  /**
   * Optional hero image for this page. Select from the media library or upload a new scoped image asset.
   */
  hero?: (number | null) | Media;
  title: string;
  /**
   * Optional localized introduction for this page.
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Which chapter this page belongs to.
   */
  chapter: number | CourseChapter;
  /**
   * Ordered reusable content items for this page. The same item cannot be added twice to one page.
   */
  contentItems?:
    | {
        /**
         * Select a reusable content item to place on this page.
         */
        content: number | CourseContent;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Reusable content items that can be placed on many course pages without duplicating the source content.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "course-content".
 */
export interface CourseContent {
  id: number;
  title: string;
  /**
   * Choose the content kind first. The form will then show only the fields relevant to that kind.
   */
  contentType: 'richText' | 'quote' | 'image' | 'assignment' | 'question';
  /**
   * Optional summary shown when the content item needs a short introduction.
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Which project owns this reusable content item.
   */
  project: number | Project;
  /**
   * Main rich text body for a rich text content item.
   */
  richTextBody?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Select an image from the media library or upload a new scoped image asset for this project.
   */
  image?: (number | null) | Media;
  /**
   * Optional caption or explanatory text for the image.
   */
  imageCaption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * The quoted text to display.
   */
  quoteText?: string | null;
  /**
   * Optional source, speaker, or author for the quote.
   */
  quoteAttribution?: string | null;
  /**
   * Add the questions that belong to this assignment. Their order defines question 1 of N, 2 of N, and so on.
   */
  assignmentQuestions?: (number | CourseContent)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Reusable palette definitions used by custom UI and branded content assets.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "palettes".
 */
export interface Palette {
  id: number;
  name: string;
  palette: string;
  shades?:
    | {
        shade: string;
        overrideUseDarkAccent?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'project-types';
        value: number | ProjectType;
      } | null)
    | ({
        relationTo: 'product-types';
        value: number | ProductType;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'project-groups';
        value: number | ProjectGroup;
      } | null)
    | ({
        relationTo: 'courses';
        value: number | Course;
      } | null)
    | ({
        relationTo: 'course-chapters';
        value: number | CourseChapter;
      } | null)
    | ({
        relationTo: 'course-pages';
        value: number | CoursePage;
      } | null)
    | ({
        relationTo: 'course-content';
        value: number | CourseContent;
      } | null)
    | ({
        relationTo: 'palettes';
        value: number | Palette;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  roles?: T;
  viewableProjects?: T;
  editableProjects?: T;
  managedProjects?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  kind?: T;
  availabilityScope?: T;
  project?: T;
  projectGroup?: T;
  product?: T;
  course?: T;
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "project-types_select".
 */
export interface ProjectTypesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  projects?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-types_select".
 */
export interface ProductTypesSelect<T extends boolean = true> {
  title?: T;
  products?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  isbn?: T;
  productType?: T;
  courses?: T;
  projectGroups?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  projectType?: T;
  groups?: T;
  courses?: T;
  viewers?: T;
  editors?: T;
  managers?: T;
  viewerSummary?: T;
  editorSummary?: T;
  managerSummary?: T;
  lifecycle?: T;
  isPublic?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "project-groups_select".
 */
export interface ProjectGroupsSelect<T extends boolean = true> {
  project?: T;
  products?: T;
  title?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses_select".
 */
export interface CoursesSelect<T extends boolean = true> {
  hero?: T;
  title?: T;
  isbn?: T;
  description?: T;
  project?: T;
  chapters?: T;
  products?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "course-chapters_select".
 */
export interface CourseChaptersSelect<T extends boolean = true> {
  hero?: T;
  title?: T;
  description?: T;
  course?: T;
  pages?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "course-pages_select".
 */
export interface CoursePagesSelect<T extends boolean = true> {
  hero?: T;
  title?: T;
  description?: T;
  chapter?: T;
  contentItems?:
    | T
    | {
        content?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "course-content_select".
 */
export interface CourseContentSelect<T extends boolean = true> {
  title?: T;
  contentType?: T;
  description?: T;
  project?: T;
  richTextBody?: T;
  image?: T;
  imageCaption?: T;
  quoteText?: T;
  quoteAttribution?: T;
  assignmentQuestions?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "palettes_select".
 */
export interface PalettesSelect<T extends boolean = true> {
  name?: T;
  palette?: T;
  shades?:
    | T
    | {
        shade?: T;
        overrideUseDarkAccent?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}